@startuml
entity "Cars" as car
{
  +<&key> ID : int
  --
  <&spreadsheet> Vehicle_Model_Year : int
  <&spreadsheet> Transmission_Type  : varchar
  <&spreadsheet> Rent_Price : numeric
  <&spreadsheet> Actuator_Type  : varchar
  <&spreadsheet> Engine_Displacement : float
  <&spreadsheet> Type_Of_Bodywork : varchar
  <&spreadsheet> Rental_Cost : numeric
}
@enduml