@startuml
entity "Car Features" as carFeatures
{
  +<&key> Car_ID : int
  --
  <&spreadsheet> Air_Conditioner_Type : text
  <&spreadsheet> Navigation_System_Type : text
  <&spreadsheet> Cruise_Control_Availability : bool
}
@enduml